INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',26,'f','White-European','no'),
	 ('Adult',24,'m','Latino','yes'),
	 ('Adult',27,'m','Latino','yes'),
	 ('Adult',35,'f','White-European','yes'),
	 ('Adult',36,'m','Others','no'),
	 ('Adult',17,'f','Black','no'),
	 ('Adult',64,'m','White-European','no'),
	 ('Adult',29,'m','White-European','no'),
	 ('Adult',17,'m','Asian','yes'),
	 ('Adult',33,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',18,'f','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','yes'),
	 ('Adult',31,'m','Middle Eastern ','no'),
	 ('Adult',30,'m','White-European','no'),
	 ('Adult',35,'f','Middle Eastern ','yes'),
	 ('Adult',27,'f','Black','no'),
	 ('Adult',27,'m','Middle Eastern ','no'),
	 ('Adult',42,'m','Middle Eastern ','no'),
	 ('Adult',40,'m','Pasifika','yes'),
	 ('Adult',40,'m','Middle Eastern ','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',48,'m','Black','no'),
	 ('Adult',31,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','White-European','no'),
	 ('Adult',37,'f','White-European','yes'),
	 ('Adult',55,'f','Others','no'),
	 ('Adult',18,'f','White-European','no'),
	 ('Adult',18,'f','White-European','no'),
	 ('Adult',55,'m','White-European','no'),
	 ('Adult',50,'m','Middle Eastern ','no'),
	 ('Adult',34,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',53,'f','White-European','no'),
	 ('Adult',35,'f','White-European','yes'),
	 ('Adult',20,'f','Latino','no'),
	 ('Adult',28,'f','Asian','no'),
	 ('Adult',34,'f','Middle Eastern ','yes'),
	 ('Adult',36,'f','White-European','yes'),
	 ('Adult',27,'f','White-European','no'),
	 ('Adult',53,'f','White-European','no'),
	 ('Adult',24,'f','Pasifika','no'),
	 ('Adult',24,'m','Pasifika','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',55,'m','White-European','no'),
	 ('Adult',30,'f','Asian','no'),
	 ('Adult',21,'f','Latino','no'),
	 ('Adult',35,'f','Black','no'),
	 ('Adult',383,'f','Pasifika','no'),
	 ('Adult',21,'m','Latino','yes'),
	 ('Adult',47,'m','White-European','no'),
	 ('Adult',30,'f','Asian','no'),
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',43,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',32,'f','South Asian','yes'),
	 ('Adult',44,'f','White-European','no'),
	 ('Adult',20,'f','Others','no'),
	 ('Adult',20,'f','Others','no'),
	 ('Adult',19,'m','White-European','no'),
	 ('Adult',29,'f','White-European','no'),
	 ('Adult',21,'m','Middle Eastern ','no'),
	 ('Adult',27,'m','Middle Eastern ','no'),
	 ('Adult',21,'m','Hispanic','no'),
	 ('Adult',35,'m','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',42,'m','Black','no'),
	 ('Adult',29,'f','South Asian','no'),
	 ('Adult',58,'m','Asian','no'),
	 ('Adult',21,'m','Others','no'),
	 ('Adult',21,'m','Others','no'),
	 ('Adult',37,'f','White-European','yes'),
	 ('Adult',21,'m','Hispanic','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',33,'f','Black','yes'),
	 ('Adult',20,'m','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',33,'f','White-European','yes'),
	 ('Adult',42,'f','Middle Eastern ','no'),
	 ('Adult',17,'f','White-European','no'),
	 ('Adult',27,'f','Middle Eastern ','no'),
	 ('Adult',35,'f','Middle Eastern ','yes'),
	 ('Adult',37,'m','White-European','no'),
	 ('Adult',30,'f','White-European','yes'),
	 ('Adult',29,'f','White-European','no'),
	 ('Adult',17,'f','White-European','yes'),
	 ('Adult',22,'f','Pasifika','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',19,'f','Latino','yes'),
	 ('Adult',42,'f','White-European','yes'),
	 ('Adult',37,'f','White-European','no'),
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',22,'m','Others','no'),
	 ('Adult',26,'f','Pasifika','no'),
	 ('Adult',21,'m','Pasifika','no'),
	 ('Adult',26,'f','South Asian','no'),
	 ('Adult',39,'f','Asian','no'),
	 ('Adult',26,'m','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',26,'m','Asian','no'),
	 ('Adult',21,'m','South Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',26,'m','South Asian','no'),
	 ('Adult',30,'f','White-European','no'),
	 ('Adult',19,'f','Asian','no'),
	 ('Adult',19,'f','Asian','no'),
	 ('Adult',25,'f','White-European','yes'),
	 ('Adult',23,'m','White-European','no'),
	 ('Adult',31,'m','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',27,'m','Asian','no'),
	 ('Adult',29,'f','Middle Eastern ','no'),
	 ('Adult',38,'f','White-European','no'),
	 ('Adult',23,'f','White-European','no'),
	 ('Adult',27,'m','White-European','no'),
	 ('Adult',27,'f','White-European','no'),
	 ('Adult',42,'m','White-European','no'),
	 ('Adult',20,'m','White-European','no'),
	 ('Adult',17,'f','White-European','no'),
	 ('Adult',20,'f','Black','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',28,'f','White-European','yes'),
	 ('Adult',26,'f','White-European','no'),
	 ('Adult',26,'f','White-European','no'),
	 ('Adult',31,'m','Middle Eastern ','yes'),
	 ('Adult',40,'f','White-European','no'),
	 ('Adult',39,'f','White-European','yes'),
	 ('Adult',18,'f','White-European','no'),
	 ('Adult',24,'m','Black','no'),
	 ('Adult',23,'m','South Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',27,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',22,'m','Asian','no'),
	 ('Adult',40,'f','Asian','no'),
	 ('Adult',23,'m','Asian','no'),
	 ('Adult',29,'m','South Asian','no'),
	 ('Adult',25,'m','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',27,'m','Asian','no'),
	 ('Adult',22,'m','South Asian','no'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',20,'m','White-European','no'),
	 ('Adult',19,'f','White-European','no'),
	 ('Adult',37,'f','Others','no'),
	 ('Adult',35,'m','White-European','yes'),
	 ('Adult',26,'m','Asian','no'),
	 ('Adult',23,'m','Asian','no'),
	 ('Adult',32,'f','South Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',31,'m','Asian','no'),
	 ('Adult',28,'f','Asian','no'),
	 ('Adult',29,'f','Asian','no'),
	 ('Adult',29,'f','South Asian','no'),
	 ('Adult',29,'f','Asian','no'),
	 ('Adult',31,'m','Asian','no'),
	 ('Adult',36,'m','Asian','no'),
	 ('Adult',32,'f','South Asian','no'),
	 ('Adult',34,'f','South Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',24,'f','Asian','no'),
	 ('Adult',42,'m','Asian','no'),
	 ('Adult',26,'f','Others','no'),
	 ('Adult',27,'f','Asian','no'),
	 ('Adult',36,'f','Latino','yes'),
	 ('Adult',36,'f','Latino','yes'),
	 ('Adult',55,'m','Hispanic','no'),
	 ('Adult',23,'f','Asian','no'),
	 ('Adult',22,'f','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',42,'f','Middle Eastern ','no'),
	 ('Adult',54,'m','White-European','no'),
	 ('Adult',43,'f','Black','no'),
	 ('Adult',43,'f','Black','no'),
	 ('Adult',29,'m','Middle Eastern ','no'),
	 ('Adult',29,'m','Middle Eastern ','no'),
	 ('Adult',37,'m','White-European','no'),
	 ('Adult',39,'f','White-European','no'),
	 ('Adult',18,'f','Asian','no'),
	 ('Adult',31,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',34,'m','Asian','no'),
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',28,'m','South Asian','no'),
	 ('Adult',38,'m','Others','yes'),
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',53,'f','White-European','yes'),
	 ('Adult',26,'m','White-European','no'),
	 ('Adult',37,'m','White-European','no'),
	 ('Adult',42,'m','Latino','yes'),
	 ('Adult',43,'m','Hispanic','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',32,'f','Asian','no'),
	 ('Adult',31,'m','White-European','yes'),
	 ('Adult',53,'f','White-European','no'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',38,'m','White-European','no'),
	 ('Adult',31,'m','White-European','no'),
	 ('Adult',31,'f','Pasifika','yes'),
	 ('Adult',21,'f','White-European','no'),
	 ('Adult',25,'f','White-European','no'),
	 ('Adult',25,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',60,'f','White-European','yes'),
	 ('Adult',39,'m','White-European','yes'),
	 ('Adult',53,'m','White-European','no'),
	 ('Adult',20,'m','Middle Eastern ','yes'),
	 ('Adult',25,'f','White-European','no'),
	 ('Adult',50,'m','White-European','no'),
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',37,'f','White-European','yes'),
	 ('Adult',30,'m','Asian','yes'),
	 ('Adult',32,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',34,'f','White-European','no'),
	 ('Adult',42,'m','White-European','no'),
	 ('Adult',22,'f','Black','no'),
	 ('Adult',39,'m','White-European','yes'),
	 ('Adult',18,'m','White-European','no'),
	 ('Adult',54,'f','White-European','yes'),
	 ('Adult',42,'m','White-European','no'),
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',21,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',17,'m','Asian','no'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',21,'m','Latino','no'),
	 ('Adult',31,'f','Asian','no'),
	 ('Adult',20,'m','South Asian','no'),
	 ('Adult',21,'m','White-European','no'),
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',21,'m','White-European','no'),
	 ('Adult',24,'m','Black','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','South Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',17,'m','South Asian','no'),
	 ('Adult',23,'m','Pasifika','no'),
	 ('Adult',21,'m','Asian','no'),
	 ('Adult',22,'m','Others','no'),
	 ('Adult',24,'f','Asian','no'),
	 ('Adult',34,'m','Others','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',29,'f','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',20,'m','Pasifika','no'),
	 ('Adult',23,'m','White-European','no'),
	 ('Adult',26,'m','Asian','no'),
	 ('Adult',20,'m','South Asian','no'),
	 ('Adult',41,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',35,'m','Asian','no'),
	 ('Adult',23,'m','South Asian','no'),
	 ('Adult',36,'m','White-European','no'),
	 ('Adult',33,'m','Turkish','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','South Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',27,'f','South Asian','no'),
	 ('Adult',26,'m','Asian','no'),
	 ('Adult',26,'m','Others','no'),
	 ('Adult',23,'f','Asian','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',25,'m','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',23,'m','Pasifika','no'),
	 ('Adult',34,'f','White-European','no'),
	 ('Adult',20,'f','Asian','no'),
	 ('Adult',33,'f','Black','yes'),
	 ('Adult',46,'m','White-European','no'),
	 ('Adult',17,'m','White-European','no'),
	 ('Adult',45,'f','White-European','yes'),
	 ('Adult',26,'m','Asian','no'),
	 ('Adult',38,'f','White-European','no'),
	 ('Adult',26,'m','Hispanic','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',29,'f','Hispanic','yes'),
	 ('Adult',33,'m','White-European','no'),
	 ('Adult',32,'f','Black','no'),
	 ('Adult',44,'f','White-European','no'),
	 ('Adult',47,'f','White-European','no'),
	 ('Adult',40,'m','White-European','no'),
	 ('Adult',40,'m','White-European','no'),
	 ('Adult',44,'f','White-European','no'),
	 ('Adult',56,'m','White-European','no'),
	 ('Adult',23,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',32,'f','Black','no'),
	 ('Adult',27,'m','White-European','yes'),
	 ('Adult',28,'f','White-European','yes'),
	 ('Adult',40,'f','Middle Eastern ','no'),
	 ('Adult',45,'f','White-European','no'),
	 ('Adult',19,'f','White-European','no'),
	 ('Adult',55,'m','White-European','yes'),
	 ('Adult',27,'f','White-European','no'),
	 ('Adult',19,'f','White-European','no'),
	 ('Adult',29,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',33,'f','White-European','no'),
	 ('Adult',48,'f','White-European','no'),
	 ('Adult',37,'f','Others','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',37,'f','White-European','no'),
	 ('Adult',20,'f','White-European','no'),
	 ('Adult',25,'f','Others','no'),
	 ('Adult',58,'f','Middle Eastern ','no'),
	 ('Adult',36,'f','White-European','no'),
	 ('Adult',36,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',19,'m','Hispanic','no'),
	 ('Adult',19,'m','Hispanic','no'),
	 ('Adult',22,'f','White-European','no'),
	 ('Adult',24,'f','Middle Eastern ','no'),
	 ('Adult',19,'m','Middle Eastern ','no'),
	 ('Adult',21,'m','Others','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',18,'f','Middle Eastern ','no'),
	 ('Adult',23,'f','Middle Eastern ','no'),
	 ('Adult',22,'m','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',18,'f','South Asian','yes'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',19,'m','White-European','no'),
	 ('Adult',55,'m','White-European','no'),
	 ('Adult',32,'f','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',50,'m','White-European','no'),
	 ('Adult',40,'m','White-European','no'),
	 ('Adult',47,'m','Middle Eastern ','no'),
	 ('Adult',22,'m','Middle Eastern ','no'),
	 ('Adult',19,'f','Middle Eastern ','no'),
	 ('Adult',22,'m','Middle Eastern ','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',23,'m','Middle Eastern ','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',24,'m','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',19,'m','Middle Eastern ','no'),
	 ('Adult',23,'m','Middle Eastern ','yes'),
	 ('Adult',20,'m','Others','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',21,'f','Asian','no'),
	 ('Adult',20,'f','Middle Eastern ','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',25,'m','Middle Eastern ','yes'),
	 ('Adult',20,'f','Middle Eastern ','no'),
	 ('Adult',22,'m','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',20,'f','Middle Eastern ','no'),
	 ('Adult',21,'m','Middle Eastern ','no'),
	 ('Adult',23,'f','Middle Eastern ','no'),
	 ('Adult',21,'f','Turkish','no'),
	 ('Adult',22,'f','Black','no'),
	 ('Adult',20,'f','Asian','no'),
	 ('Adult',21,'f','Others','no'),
	 ('Adult',26,'m','Middle Eastern ','no'),
	 ('Adult',23,'f','Black','no'),
	 ('Adult',19,'f','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',20,'f','Middle Eastern ','no'),
	 ('Adult',19,'f','Black','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',19,'f','South Asian','no'),
	 ('Adult',22,'f','Middle Eastern ','no'),
	 ('Adult',20,'f','Middle Eastern ','no'),
	 ('Adult',21,'m','Middle Eastern ','no'),
	 ('Adult',24,'f','Others','no'),
	 ('Adult',18,'f','Middle Eastern ','no'),
	 ('Adult',19,'f','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',19,'f','Middle Eastern ','no'),
	 ('Adult',31,'m','Middle Eastern ','no'),
	 ('Adult',19,'m','Middle Eastern ','no'),
	 ('Adult',21,'f','Middle Eastern ','no'),
	 ('Adult',20,'m','Middle Eastern ','no'),
	 ('Adult',26,'f','Middle Eastern ','no'),
	 ('Adult',27,'m','Middle Eastern ','no'),
	 ('Adult',23,'f','Middle Eastern ','no'),
	 ('Adult',23,'m','Middle Eastern ','no'),
	 ('Adult',23,'m','Turkish','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','Asian','yes'),
	 ('Adult',32,'f','Black','no'),
	 ('Adult',61,'m','White-European','yes'),
	 ('Adult',35,'f','White-European','no'),
	 ('Adult',34,'f','White-European','no'),
	 ('Adult',23,'f','Middle Eastern ','no'),
	 ('Adult',19,'f','White-European','no'),
	 ('Adult',36,'f','Others','no'),
	 ('Adult',23,'m','White-European','no'),
	 ('Adult',17,'m','Black','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',33,'m','White-European','yes'),
	 ('Adult',23,'f','Asian','no'),
	 ('Adult',35,'f','White-European','yes'),
	 ('Adult',21,'m','White-European','yes'),
	 ('Adult',20,'f','White-European','no'),
	 ('Adult',29,'m','White-European','no'),
	 ('Adult',59,'m','White-European','no'),
	 ('Adult',18,'f','White-European','no'),
	 ('Adult',19,'f','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','Middle Eastern ','no'),
	 ('Adult',36,'f','White-European','no'),
	 ('Adult',17,'f','Black','no'),
	 ('Adult',52,'m','White-European','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',27,'m','Latino','no'),
	 ('Adult',52,'f','White-European','no'),
	 ('Adult',45,'f','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',25,'f','Others','no'),
	 ('Adult',29,'f','White-European','no'),
	 ('Adult',29,'f','White-European','no'),
	 ('Adult',18,'m','White-European','yes'),
	 ('Adult',18,'m','White-European','no'),
	 ('Adult',17,'m','White-European','no'),
	 ('Adult',27,'f','Asian','no'),
	 ('Adult',22,'f','Asian','no'),
	 ('Adult',23,'m','Asian','no'),
	 ('Adult',25,'m','Latino','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',23,'f','South Asian','no'),
	 ('Adult',29,'m','Asian','no'),
	 ('Adult',27,'f','Asian','no'),
	 ('Adult',27,'f','Asian','no'),
	 ('Adult',43,'f','South Asian','no'),
	 ('Adult',26,'f','Asian','no'),
	 ('Adult',30,'f','Asian','no'),
	 ('Adult',23,'m','White-European','no'),
	 ('Adult',29,'f','Asian','no'),
	 ('Adult',37,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',28,'f','White-European','no'),
	 ('Adult',25,'m','South Asian','no'),
	 ('Adult',25,'m','Others','no'),
	 ('Adult',43,'m','White-European','no'),
	 ('Adult',30,'f','White-European','no'),
	 ('Adult',18,'m','Black','no'),
	 ('Adult',18,'f','White-European','no'),
	 ('Adult',30,'m','Others','no'),
	 ('Adult',31,'f','White-European','no'),
	 ('Adult',33,'m','Latino','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',33,'m','Latino','no'),
	 ('Adult',26,'m','White-European','no'),
	 ('Adult',61,'f','White-European','no'),
	 ('Adult',46,'m','Others','no'),
	 ('Adult',33,'m','Asian','no'),
	 ('Adult',38,'f','Black','no'),
	 ('Adult',44,'m','Black','no'),
	 ('Adult',48,'f','Black','yes'),
	 ('Adult',42,'f','Latino','no'),
	 ('Adult',37,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',23,'f','White-European','yes'),
	 ('Adult',24,'m','White-European','yes'),
	 ('Adult',41,'m','Asian','no'),
	 ('Adult',27,'m','White-European','no'),
	 ('Adult',46,'f','White-European','yes'),
	 ('Adult',40,'f','White-European','no'),
	 ('Adult',22,'f','White-European','no'),
	 ('Adult',42,'m','White-European','no'),
	 ('Adult',18,'f','Asian','no'),
	 ('Adult',44,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',30,'f','White-European','no'),
	 ('Adult',42,'m','White-European','no'),
	 ('Adult',35,'f','White-European','yes'),
	 ('Adult',40,'m','Black','no'),
	 ('Adult',38,'m','Middle Eastern ','no'),
	 ('Adult',26,'f','White-European','yes'),
	 ('Adult',27,'f','White-European','no'),
	 ('Adult',47,'f','White-European','yes'),
	 ('Adult',21,'m','Black','yes'),
	 ('Adult',37,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',19,'f','Others','no'),
	 ('Adult',32,'m','Asian','no'),
	 ('Adult',46,'f','White-European','yes'),
	 ('Adult',29,'m','Black','no'),
	 ('Adult',30,'f','Black','no'),
	 ('Adult',32,'f','Latino','no'),
	 ('Adult',35,'f','White-European','no'),
	 ('Adult',22,'m','White-European','no'),
	 ('Adult',32,'f','White-European','no'),
	 ('Adult',24,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',24,'m','White-European','no'),
	 ('Adult',49,'f','Middle Eastern ','no'),
	 ('Adult',30,'f','Asian','no'),
	 ('Adult',30,'f','Asian','yes'),
	 ('Adult',35,'f','White-European','no'),
	 ('Adult',35,'f','White-European','no'),
	 ('Adult',37,'f','White-European','yes'),
	 ('Adult',43,'m','White-European','no'),
	 ('Adult',52,'m','White-European','no'),
	 ('Adult',44,'m','White-European','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',46,'f','White-European','yes'),
	 ('Adult',42,'f','White-European','yes'),
	 ('Adult',20,'m','Asian','no'),
	 ('Adult',18,'m','Middle Eastern ','no'),
	 ('Adult',38,'m','White-European','no'),
	 ('Adult',24,'f','Latino','yes'),
	 ('Adult',29,'m','Turkish','no'),
	 ('Adult',22,'f','White-European','no'),
	 ('Adult',19,'f','White-European','no'),
	 ('Adult',39,'f','White-European','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',17,'m','Black','no'),
	 ('Adult',19,'f','Middle Eastern ','no'),
	 ('Adult',18,'m','White-European','no'),
	 ('Adult',28,'f','Turkish','no'),
	 ('Adult',29,'m','Asian','no'),
	 ('Adult',48,'m','White-European','no'),
	 ('Adult',27,'f','White-European','yes'),
	 ('Adult',34,'f','White-European','no'),
	 ('Adult',31,'m','White-European','no'),
	 ('Adult',44,'m','White-European','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',25,'f','White-European','no'),
	 ('Adult',25,'f','White-European','no'),
	 ('Adult',20,'m','White-European','no'),
	 ('Adult',43,'m','White-European','no'),
	 ('Adult',36,'f','White-European','yes'),
	 ('Adult',30,'f','Asian','yes'),
	 ('Adult',44,'m','Black','no'),
	 ('Adult',40,'f','Black','no'),
	 ('Adult',40,'f','Black','no'),
	 ('Adult',40,'f','Black','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',30,'m','Others','no'),
	 ('Adult',47,'f','White-European','no'),
	 ('Adult',21,'m','Black','no'),
	 ('Adult',21,'m','Black','no'),
	 ('Adult',21,'f','Asian','no'),
	 ('Adult',29,'f','Asian','no'),
	 ('Adult',22,'m','Middle Eastern ','no'),
	 ('Adult',51,'m','White-European','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',22,'m','Others','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',22,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',26,'f','South Asian','no'),
	 ('Adult',33,'f','Asian','no'),
	 ('Adult',23,'m','Asian','no'),
	 ('Adult',42,'f','Asian','no'),
	 ('Adult',26,'f','Asian','no'),
	 ('Adult',29,'f','Asian','no'),
	 ('Adult',35,'f','Asian','no'),
	 ('Adult',25,'f','South Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',28,'f','Asian','no'),
	 ('Adult',33,'m','White-European','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',25,'m','Asian','no'),
	 ('Adult',24,'m','Asian','no'),
	 ('Adult',27,'f','South Asian','no'),
	 ('Adult',22,'m','South Asian','no'),
	 ('Adult',21,'f','South Asian','no'),
	 ('Adult',27,'f','South Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',23,'m','South Asian','no'),
	 ('Adult',22,'m','Asian','no'),
	 ('Adult',23,'f','South Asian','no'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',33,'m','Asian','no'),
	 ('Adult',24,'f','South Asian','no'),
	 ('Adult',22,'f','Asian','no'),
	 ('Adult',22,'m','Asian','no'),
	 ('Adult',29,'f','South Asian','no'),
	 ('Adult',22,'f','Asian','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',21,'m','Asian','no'),
	 ('Adult',23,'m','Asian','no'),
	 ('Adult',23,'f','Others','no'),
	 ('Adult',23,'f','Asian','no'),
	 ('Adult',32,'m','Asian','no'),
	 ('Adult',27,'m','Asian','no'),
	 ('Adult',28,'f','Asian','no'),
	 ('Adult',25,'f','Middle Eastern ','no'),
	 ('Adult',22,'m','Black','no'),
	 ('Adult',36,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',21,'f','White-European','no'),
	 ('Adult',18,'m','Black','no'),
	 ('Adult',49,'m','Black','no'),
	 ('Adult',18,'m','Asian','no'),
	 ('Adult',29,'m','Latino','no'),
	 ('Adult',37,'f','Middle Eastern ','no'),
	 ('Adult',17,'m','Middle Eastern ','no'),
	 ('Adult',38,'f','Middle Eastern ','no'),
	 ('Adult',18,'m','White-European','no'),
	 ('Adult',31,'f','Middle Eastern ','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',33,'m','Middle Eastern ','no'),
	 ('Adult',32,'f','Middle Eastern ','no'),
	 ('Adult',30,'f','White-European','yes'),
	 ('Adult',30,'m','Asian','no'),
	 ('Adult',38,'f','White-European','yes'),
	 ('Adult',22,'m','Asian','no'),
	 ('Adult',36,'m','others','no'),
	 ('Adult',20,'f','White-European','no'),
	 ('Adult',40,'f','Others','yes'),
	 ('Adult',25,'m','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',17,'m','White-European','no'),
	 ('Adult',34,'m','White-European','no'),
	 ('Adult',50,'f','Middle Eastern ','no'),
	 ('Adult',38,'m','White-European','no'),
	 ('Adult',47,'m','White-European','no'),
	 ('Adult',30,'m','Others','no'),
	 ('Adult',21,'m','Hispanic','no'),
	 ('Adult',21,'m','White-European','no'),
	 ('Adult',31,'m','Latino','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',27,'f','White-European','no'),
	 ('Adult',24,'f','White-European','no'),
	 ('Adult',35,'m','White-European','no'),
	 ('Adult',18,'m','Black','no'),
	 ('Adult',43,'f','Black','no'),
	 ('Adult',44,'m','White-European','yes'),
	 ('Adult',40,'m','White-European','yes'),
	 ('Adult',49,'f','Hispanic','no'),
	 ('Adult',24,'m','Hispanic','no'),
	 ('Adult',30,'f','White-European','yes');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',53,'m','Hispanic','no'),
	 ('Adult',38,'m','White-European','yes'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',26,'m','Black','no'),
	 ('Adult',39,'f','White-European','no'),
	 ('Adult',31,'f','Asian','no'),
	 ('Adult',24,'m','Black','no'),
	 ('Adult',28,'m','White-European','no'),
	 ('Adult',31,'f','White-European','no');
INSERT INTO adult_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Adult',27,'m','White-European','no'),
	 ('Adult',28,'m','Latino','no'),
	 ('Adult',31,'m','Turkish','yes'),
	 ('Adult',46,'f','Asian','no'),
	 ('Adult',27,'f','Pasifika','no'),
	 ('Adult',25,'f','White-European','no'),
	 ('Adult',34,'m','Hispanic','no'),
	 ('Adult',35,'m','South Asian','no'),
	 ('Adult',26,'f','White-European','no');
