INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',6,'m','Others','no'),
	 ('Child',6,'m','Middle Eastern ','no'),
	 ('Child',5,'m','Others','no'),
	 ('Child',5,'m','White-European','no'),
	 ('Child',5,'f','Middle Eastern ','no'),
	 ('Child',11,'f','Middle Eastern ','no'),
	 ('Child',10,'m','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'f','Black','no'),
	 ('Child',6,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',7,'m','Others','no'),
	 ('Child',11,'m','White-European','yes'),
	 ('Child',5,'m','White-European','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',6,'f','South Asian','no'),
	 ('Child',6,'m','White-European','yes'),
	 ('Child',6,'f','Middle Eastern ','no'),
	 ('Child',5,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'f','Others','yes'),
	 ('Child',11,'m','White-European','no'),
	 ('Child',6,'m','Pasifika','no'),
	 ('Child',5,'m','South Asian','no'),
	 ('Child',6,'m','South Asian','no'),
	 ('Child',7,'f','Middle Eastern ','no'),
	 ('Child',7,'m','Asian','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',4,'m','Middle Eastern ','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',6,'f','Middle Eastern ','no'),
	 ('Child',10,'m','Middle Eastern ','no'),
	 ('Child',4,'f','Middle Eastern ','no'),
	 ('Child',4,'f','Middle Eastern ','no'),
	 ('Child',6,'f','White-European','no'),
	 ('Child',7,'m','Middle Eastern ','yes'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',7,'m','White-European','no'),
	 ('Child',5,'m','White-European','no'),
	 ('Child',4,'f','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',9,'f','Middle Eastern ','no'),
	 ('Child',4,'m','Hispanic','yes'),
	 ('Child',4,'m','Turkish','no'),
	 ('Child',9,'m','White-European','no'),
	 ('Child',4,'f','White-European','no'),
	 ('Child',9,'m','Asian','no'),
	 ('Child',8,'m','Middle Eastern ','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'m','White-European','yes');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',7,'m','Asian','no'),
	 ('Child',7,'f','White-European','no'),
	 ('Child',6,'m','South Asian','no'),
	 ('Child',5,'f','Middle Eastern ','no'),
	 ('Child',8,'f','Middle Eastern ','yes'),
	 ('Child',5,'m','White-European','no'),
	 ('Child',11,'f','Others','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'m','Latino','yes'),
	 ('Child',7,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'m','White-European','no'),
	 ('Child',7,'m','White-European','yes'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',5,'m','Asian','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',11,'f','White-European','no'),
	 ('Child',11,'f','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',5,'m','Latino','yes'),
	 ('Child',6,'m','Hispanic','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'f','White-European','no'),
	 ('Child',11,'f','White-European','yes'),
	 ('Child',5,'m','Asian','no'),
	 ('Child',5,'m','Asian','no'),
	 ('Child',6,'m','Latino','no'),
	 ('Child',7,'m','Hispanic','no'),
	 ('Child',11,'m','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'m','White-European','yes'),
	 ('Child',7,'m','White-European','yes');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',11,'f','White-European','yes'),
	 ('Child',6,'f','Asian','no'),
	 ('Child',9,'f','White-European','no'),
	 ('Child',10,'m','Others','no'),
	 ('Child',4,'m','Asian','yes'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',10,'m','White-European','no'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',11,'m','Asian','no'),
	 ('Child',7,'m','Asian','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'f','White-European','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',11,'m','Asian','no'),
	 ('Child',10,'f','Asian','no'),
	 ('Child',6,'f','White-European','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',4,'m','Asian','yes'),
	 ('Child',4,'m','Asian','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',10,'m','White-European','no'),
	 ('Child',7,'m','White-European','no'),
	 ('Child',6,'f','White-European','no'),
	 ('Child',5,'m','Asian','no'),
	 ('Child',4,'f','Asian','no'),
	 ('Child',9,'m','Asian','no'),
	 ('Child',4,'f','White-European','no'),
	 ('Child',10,'m','White-European','no'),
	 ('Child',9,'m','White-European','no'),
	 ('Child',5,'m','White-European','yes');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'f','Black','no'),
	 ('Child',4,'m','White-European','yes'),
	 ('Child',6,'m','White-European','no'),
	 ('Child',4,'f','White-European','no'),
	 ('Child',5,'f','Hispanic','no'),
	 ('Child',9,'m','White-European','yes'),
	 ('Child',7,'f','White-European','no'),
	 ('Child',10,'f','White-European','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',4,'m','Asian','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',7,'f','White-European','no'),
	 ('Child',4,'m','Black','no'),
	 ('Child',10,'m','White-European','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',4,'m','South Asian','yes'),
	 ('Child',4,'m','Black','yes'),
	 ('Child',7,'m','White-European','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',5,'f','White-European','no'),
	 ('Child',6,'m','Others','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',6,'f','Asian','no'),
	 ('Child',6,'f','White-European','yes'),
	 ('Child',9,'m','White-European','yes'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',9,'m','White-European','no'),
	 ('Child',9,'f','White-European','yes'),
	 ('Child',7,'m','Black','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',10,'f','Others','no'),
	 ('Child',8,'m','Middle Eastern ','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',6,'m','Others','no'),
	 ('Child',11,'f','White-European','no'),
	 ('Child',5,'f','White-European','no'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',11,'m','White-European','no'),
	 ('Child',11,'f','Others','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',9,'m','White-European','no'),
	 ('Child',4,'m','Asian','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',4,'m','Asian','no'),
	 ('Child',11,'m','Hispanic','no'),
	 ('Child',10,'f','Asian','no'),
	 ('Child',11,'m','Asian','no'),
	 ('Child',4,'m','Black','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',6,'f','Black','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',8,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',11,'m','Hispanic','no'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',8,'m','Black','no'),
	 ('Child',4,'m','Pasifika','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',9,'m','White-European','yes'),
	 ('Child',9,'m','White-European','yes'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',5,'m','South Asian','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',7,'f','Asian','no'),
	 ('Child',4,'f','White-European','no'),
	 ('Child',5,'f','White-European','no'),
	 ('Child',6,'m','Asian','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',5,'m','Latino','yes'),
	 ('Child',5,'m','Latino','yes'),
	 ('Child',6,'m','White-European','no'),
	 ('Child',8,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',5,'m','South Asian','no'),
	 ('Child',4,'f','Asian','yes'),
	 ('Child',6,'m','White-European','no'),
	 ('Child',11,'m','Turkish','yes'),
	 ('Child',6,'m','Others','no'),
	 ('Child',4,'f','Hispanic','no'),
	 ('Child',8,'m','White-European','no'),
	 ('Child',4,'m','White-European','yes'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',6,'m','White-European','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',8,'m','White-European','no'),
	 ('Child',9,'m','Black','no'),
	 ('Child',8,'f','South Asian','no'),
	 ('Child',5,'m','South Asian','no'),
	 ('Child',5,'m','Middle Eastern ','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',10,'m','White-European','no'),
	 ('Child',4,'m','Others','no'),
	 ('Child',7,'f','Asian','no'),
	 ('Child',11,'f','Latino','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',11,'m','Asian','no'),
	 ('Child',11,'f','White-European','yes'),
	 ('Child',9,'m','South Asian','no'),
	 ('Child',6,'m','South Asian','no'),
	 ('Child',5,'m','Middle Eastern ','no'),
	 ('Child',5,'m','Middle Eastern ','no'),
	 ('Child',10,'m','Middle Eastern ','yes'),
	 ('Child',7,'m','Middle Eastern ','no'),
	 ('Child',7,'m','Middle Eastern ','no'),
	 ('Child',7,'m','Middle Eastern ','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',9,'f','Middle Eastern ','no'),
	 ('Child',5,'m','Middle Eastern ','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',5,'m','Asian','yes'),
	 ('Child',4,'f','South Asian','no'),
	 ('Child',5,'m','South Asian','no'),
	 ('Child',5,'m','Black','no'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',6,'m','Asian','no'),
	 ('Child',6,'f','Black','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',5,'m','Asian','no'),
	 ('Child',11,'m','White-European','no'),
	 ('Child',10,'m','Black','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',5,'m','Others','no'),
	 ('Child',9,'m','Middle Eastern ','no'),
	 ('Child',4,'m','Asian','no'),
	 ('Child',4,'f','White-European','yes'),
	 ('Child',5,'m','Black','no'),
	 ('Child',8,'m','White-European','yes');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',8,'m','White-European','no'),
	 ('Child',6,'m','Asian','no'),
	 ('Child',11,'m','Asian','no'),
	 ('Child',10,'f','Asian','no'),
	 ('Child',6,'f','White-European','no'),
	 ('Child',6,'m','Asian','yes'),
	 ('Child',4,'m','Black','yes'),
	 ('Child',4,'m','White-European','no'),
	 ('Child',4,'f','White-European','no'),
	 ('Child',5,'m','Others','no');
INSERT INTO child_log_regression_table (patient_type,age,gender,ethnicity,autism) VALUES
	 ('Child',10,'f','White-European','no'),
	 ('Child',10,'f','White-European','no'),
	 ('Child',5,'f','Latino','no'),
	 ('Child',7,'f','White-European','yes'),
	 ('Child',7,'f','White-European','yes'),
	 ('Child',4,'m','Latino','no'),
	 ('Child',4,'m','South Asian','no'),
	 ('Child',4,'f','South Asian','no');
